FORMAT: 1A

# VendorSpace
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Notes
Notes related resources of the **Notes API**

## Vendors Collection [/vendor{?lng,lat}]
### List all vendors near user location [GET]
+ Parameters
    + lng (required, number) ... longitude
    + lat (required, number) ... latitude
+ Response 200 (application/json)

        [{
          "id": 1, 
          "name": "Kanapkowo",
          "productCount": 3,
          "imageUrl": "http://uk.eonline.com/eol_images/Entire_Site/2013825/rs_560x415-130925143046-1024.Sandwich.jl.092513_copy.jpg",
          "latitude": 50.048289,
          "longitude": 19.959646
        }, {
          "id": 2, 
          "name": "FoodTruck",
          "productCount": 4,
          "imageUrl": "http://www.findlafoodtrucks.com/blog/wp-content/uploads/2010/09/kabobmenu.jpg",
          "latitude": 50.058289,
          "longitude": 19.957646
        }]

## Vendor information [/vendor/{id}]
Get detailed information about vendor

+ Parameters
    + id (required, number, `1`) ... vendor ID

### Retrieve a Note [GET]
+ Response 200 (application/json)

         {
           "id": 2, 
           "name": "FoodTruck",
           "productCount": 4,
           "imageUrl": "http://www.findlafoodtrucks.com/blog/wp-content/uploads/2010/09/kabobmenu.jpg",
           "latitude": 50.058289,
           "longitude": 19.957646
         }



## Vendor Product list [/vendor/{id}/product]
Get list of products for given vendor

### Retrive products list [GET]
+ Response 200 (application/json)

        [
          {
            "id": 1,
            "name": "gulasz ze słonia",
            "price": 2.23,
            "currency": "PLN"
          }
        ]